export const projects = [
  // --- E-commerce & dashboards first: this is what we're selling ---
  {
    id: "1",
    image: "/zentstores.png",
    title: "Zentstores",
    description:
      "Multi-vendor e-commerce platform where independent sellers run their own storefronts. I built the full storefront experience and the vendor tooling — product management, order flow, and payouts view. Next.js, TypeScript, Redux, Tailwind. Vendor onboarding takes under 5 minutes.",
    tech: ["Next.Js", "Typescript", "Jest", "Redux", "Tailwind"],
    category: "Web Apps",
    link: "https://www.zentstores.com/",
    source: "",
  },
  {
    id: "2",
    image: "/zent-vendor.png",
    title: "Zentstores Vendor Dashboard",
    description:
      "Merchants needed one place to run their store without spreadsheets. I built the dashboard they work in daily — sales analytics, inventory control, order management, and customer insights, updating in real time. Next.js, TypeScript, Redux Toolkit, shadcn/ui. One screen replaces the whole back office.",
    tech: ["Next.Js", "Typescript", "Shadcn", "Redux Toolkit", "Tailwind"],
    category: "Admin Dashboards",
    link: "https://app.zentstores.com/",
    source: "",
  },
  {
    id: "3",
    image: "/zent-storefront.png",
    title: "Zentstore StoreFront",
    description:
      "A user-facing online storefront where customers can browse, order, and engage—built for seamless buying experiences and optimized for merchant sales.",
    tech: ["Next.Js", "Typescript", "Shadcn"],
    category: "Web Apps",
    link: "https://demilade.zentstore.com/",
    source: "",
  },
  {
    id: "4",
    image: "/kukeat.png",
    title: "Kukeat",
    description:
      "Nigerian shoppers wanted market-fresh groceries without the market trip. I built the full storefront — catalogue browsing, cart, checkout, and delivery ordering — designed mobile-first for how customers actually shop. Next.js, Tailwind. Live and taking orders at kukeat.com.",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://www.kukeat.com/",
    source: "",
  },
  {
    id: "5",
    image: "/bookxity.png",
    title: "Bookxity",
    description:
      "An online bookstore needed a fast storefront with a catalogue non-developers could update. I built the full e-commerce flow — browsing, cart, and checkout — with content managed in Sanity CMS. Next.js, Tailwind, Sanity. New titles go live without touching code.",
    tech: ["Next Js", "Tailwind", "Sanity"],
    category: "Web Apps",
    link: "https://book-xity-ecommerce.vercel.app/",
    source: "https://github.com/Demiladeala/bookXity_ecommerce",
  },
  {
    id: "6",
    image: "/chowopa.png",
    title: "Chowopa",
    description:
      "A multi-store marketplace where several vendors sell under one roof. I built the customer-facing experience — store browsing, product pages, and cart flow working consistently across every storefront. React, Tailwind. Open source — the code is public on GitHub.",
    tech: ["React", "Css", "Tailwind"],
    category: "Web Apps",
    link: "https://chowopa-v2-test.netlify.app/",
    source: "https://github.com/Fantom-01/chowopa-v2",
  },
  {
    id: "7",
    image: "/abujaroommates.png",
    title: "Abuja Roommates",
    description:
      "AbujaRoommates is a luxury serviced-apartment platform offering short-let stays and lease options across major West-African cities. With beautifully furnished units, prime locations, and seamless booking, it delivers comfort and convenience to travelers and tenants alike.",
    tech: ["Next Js", "RTK Query", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://abujaroommates.com/",
    source: "",
  },
  {
    id: "8",
    image: "/roommate-portal.png",
    title: "Abuja Roommates Host Portal",
    description:
      "A comprehensive host and guest portal for luxury serviced apartments",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Admin Dashboards",
    link: "https://app.abujaroommates.com/",
    source: "",
  },
  // --- Other client work & products ---
  {
    id: "9",
    image: "/lockedin.webp",
    title: "LockedIN",
    description:
      "A productivity app that drives consistency and focus through partner co-working, gamification, and community accountability.",
    tech: [
      "Jitsi Video Conferencing",
      "Websocket",
      "React Native",
      "Nativewind",
      "",
    ],
    category: "Mobile Apps",
    link: "https://play.google.com/store/apps/details?id=com.lockedinpartner.lockedin&hl=en",
    source: "",
    contain: true,
  },
  {
    id: "10",
    image: "/wander.png",
    title: "Wander",
    description:
      "A travel-platform built to simplify exploration by uniting curated destination guides, interactive maps, and real-time insights—helping adventure-seekers discover hidden gems, plan intelligently, and experience more of the world with less effort.",
    tech: ["GSAP", "Three Js", "React", "Shadcn"],
    category: "Web Apps",
    link: "https://www.gowanderr.com/",
    source: "",
  },
  {
    id: "11",
    image: "/64sqr.png",
    title: "64sqrs",
    description:
      "64SQRS is a live chess-tournament platform that lets players create, manage, and join tournaments effortlessly. It offers real-time pairing, live leaderboards, and smooth match tracking—bringing competitive chess online with speed and precision.",
    tech: ["NextJs", "Framer motion", "Zustand", "Tailwind", "React", "Css"],
    category: "Web Apps",
    link: "https://64sqrs.live/",
    source: "",
  },
  {
    id: "12",
    image: "/freedom.png",
    title: "Freedomozcare",
    description:
      "Freedom Oz Care — An NDIS-registered provider empowering people with disabilities through inclusive, person-centered care and community engagement across Australia.",
    tech: ["Next Js", "React", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://www.freedomozcare.com.au/",
    source: "",
  },
  {
    id: "13",
    image: "/radiantcare.png",
    title: "RadiantCareServices",
    description:
      "Radiant Care Services — NDIS provider across VIC and NSW, offering customized disability support, short-term accommodation, and community participation services that empower individuals to live independently and engage fully in their communities.",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://www.radiant-care-services.com/",
    source: "",
  },
  {
    id: "14",
    image: "/elite.png",
    title: "Elite Homes",
    description: "A Fullstack Real Estate Website",
    tech: ["Next Js", "Prisma", "Supabase", "Tailwind", "Css"],
    category: "Fullstack",
    link: "https://real-estate-9l1i450tu-demiladeala.vercel.app/",
    source: "https://github.com/Demiladeala/real-estate-app",
  },
  {
    id: "15",
    image: "/c-gen.png",
    title: "Conquering Generations",
    description: "A Church Fundraiser platform",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://demiladeala-getlinked.vercel.app/",
    source: "",
  },
  // --- Experiments & smaller builds ---
  {
    id: "16",
    image: "/getlinked.png",
    title: "Getlinked",
    description: "A web hackathon design",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://demiladeala-getlinked.vercel.app/",
    source: "https://github.com/Demiladeala/Demiladeala-Getlinked",
  },
  {
    id: "17",
    image: "/gymapp.png",
    title: "GYM-APP LANDING PAGE",
    description: "Gym Landing page",
    tech: ["React", "Typescript", "Tailwind"],
    category: "Web Apps",
    link: "https://gym-app-typescript-jet.vercel.app/",
    source: "https://github.com/Demiladeala/gym-app-typescript",
  },
  {
    id: "18",
    image: "/expense.png",
    title: "React Expense Tracker",
    description: "This is an application for tracking your expense",
    tech: ["React", "Context API"],
    category: "Web Apps",
    link: "https://react-hooks-and-context-api.vercel.app/",
    source: "https://github.com/Demiladeala/React-hooks-and-Context-API",
  },
  {
    id: "19",
    image: "/into-github.png",
    title: "Introduction to Github",
    description: "",
    tech: ["Technical writing"],
    category: "Technical writing",
    link: "https://dev.to/demilade/introduction-to-github-2hd9",
    source: "",
  },
  // --- Web3 last: kept for range, not the lead story ---
  {
    id: "20",
    image: "/juicy.png",
    title: "Juicy pay",
    description:
      "JuicyPay is a Web3 mobile platform enabling instant peer-to-peer crypto transfers and seamless token swaps—all in one secure, intuitive app built for speed and simplicity.",
    tech: ["React", "Next Js", "Tailwind", "Framer motion"],
    category: "Web3",
    link: "https://juicypay.app/",
    source: "",
  },
  {
    id: "21",
    image: "/roybits.png",
    title: "Roybits",
    description: "Digital Assets Exchange Web3 platform",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web3",
    link: "https://roybits.vercel.app/",
    source: "",
  },
];
