export const projects = [
  {
    id: "1",
    image: "/zentstores.png",
    title: "Zentstores",
    description:
      "ZentStores gives small to medium-sized businesses a modern, mobile-first commerce stack with the polish of enterprise tooling and the speed of launch-first solutions.",
    tech: ["Next.Js", "Typescript", "Jest", "Redux", "Tailwind"],
    category: "Web Apps",
    link: "https://www.zentstores.com/",
    source: "",
  },
  {
    id: "2",
    image: "/zent-vendor.png",
    title: "Zentstores Vendor Dashboard",
    description:
      "A data-driven dashboard for merchants to manage sales, orders, inventory, customers, and analytics all in one place. Built for real-time insights, easy inventory control, and smarter business decisions.",
    tech: ["Next.Js", "Typescript", "Shadcn", "Redux Toolkit", "Tailwind"],
    category: "Admin Dashboards",
    link: "https://app.zentstores.com/",
    source: "",
  },
  {
    id: "3",
    image: "/zent-storefront.png",
    title: "Zentstore StoreFront",
    description:
      "A user-facing online storefront where customers can browse, order, and engage—built for seamless buying experiences and optimized for merchant sales.",
    tech: ["Next.Js", "Typescript", "Shadcn"],
    category: "Web Apps",
    link: "https://demilade.zentstore.com/",
    source: "",
  },
  {
    id: "4",
    image: "/lockedin.webp",
    title: "LockedIN",
    description:
      "A productivity app that drives consistency and focus through partner co-working, gamification, and community accountability.",
    tech: [
      "Jitsi Video Conferencing",
      "Websocket",
      "React Native",
      "Nativewind",
      "",
    ],
    category: "Mobile Apps",
    link: "https://play.google.com/store/apps/details?id=com.lockedinpartner.lockedin&hl=en",
    source: "",
    contain: true,
  },
  {
    id: "5",
    image: "/wander.png",
    title: "Wander",
    description:
      "A travel-platform built to simplify exploration by uniting curated destination guides, interactive maps, and real-time insights—helping adventure-seekers discover hidden gems, plan intelligently, and experience more of the world with less effort.",
    tech: ["GSAP", "Three Js", "React", "Shadcn"],
    category: "Web Apps",
    link: "https://www.gowanderr.com/",
    source: "",
  },
  {
    id: "6",
    image: "/64sqr.png",
    title: "64sqrs",
    description:
      "64SQRS is a live chess-tournament platform that lets players create, manage, and join tournaments effortlessly. It offers real-time pairing, live leaderboards, and smooth match tracking—bringing competitive chess online with speed and precision.",
    tech: ["NextJs", "Framer motion", "Zustand", "Tailwind", "React", "Css"],
    category: "Web Apps",
    link: "https://64sqrs.live/",
    source: "",
  },
  {
    id: "7",
    image: "/juicy.png",
    title: "Juicy pay",
    description:
      "JuicyPay is a Web3 mobile platform enabling instant peer-to-peer crypto transfers and seamless token swaps—all in one secure, intuitive app built for speed and simplicity.",
    tech: ["React", "Next Js", "Tailwind", "Framer motion"],
    category: "Web3",
    link: "https://juicypay.app/",
    source: "",
  },
  {
    id: "8",
    image: "/kukeat.png",
    title: "Kukeat",
    description:
      "Kukeat is a Nigerian online grocery platform that brings market-fresh foodstuffs to your doorstep, offering a wide catalogue of essentials, convenient ordering, and delivery right to your home.",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://www.kukeat.com/",
    source: "",
  },
  {
    id: "9",
    image: "/abujaroommates.png",
    title: "Abuja Roommates",
    description:
      "AbujaRoommates is a luxury serviced-apartment platform offering short-let stays and lease options across major West-African cities. With beautifully furnished units, prime locations, and seamless booking, it delivers comfort and convenience to travelers and tenants alike.",
    tech: ["Next Js", "RTK Query", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://abujaroommates.com/",
    source: "",
  },
  {
    id: "9",
    image: "/roommate-portal.png",
    title: "Abuja Roommates Host Portal",
    description:
      "A comprehensive host and guest portal for luxury serviced apartments",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Admin Dashboards",
    link: "https://app.abujaroommates.com/",
    source: "",
  },
  {
    id: "10",
    image: "/getlinked.png",
    title: "Getlinked",
    description: "A web hackathon design",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://demiladeala-getlinked.vercel.app/",
    source: "https://github.com/Demiladeala/Demiladeala-Getlinked",
  },
  {
    id: "11",
    image: "/elite.png",
    title: "Elite Homes",
    description: "A Fullstack Real Estate Website",
    tech: ["Next Js", "Prisma", "Supabase", "Tailwind", "Css"],
    category: "Fullstack",
    link: "https://real-estate-9l1i450tu-demiladeala.vercel.app/",
    source: "https://github.com/Demiladeala/real-estate-app",
  },
  {
    id: "12",
    image: "/into-github.png",
    title: "Introduction to Github",
    description: "",
    tech: ["Technical writing"],
    category: "Technical writing",
    link: "https://dev.to/demilade/introduction-to-github-2hd9",
    source: "",
  },
  {
    id: "13",
    image: "/freedom.png",
    title: "Freedomozcare",
    description:
      "Freedom Oz Care — An NDIS-registered provider empowering people with disabilities through inclusive, person-centered care and community engagement across Australia.",
    tech: ["Next Js", "React", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://www.freedomozcare.com.au/",
    source: "",
  },
  {
    id: "14",
    image: "/radiantcare.png",
    title: "RadiantCareServices",
    description:
      "Radiant Care Services — NDIS provider across VIC and NSW, offering customized disability support, short-term accommodation, and community participation services that empower individuals to live independently and engage fully in their communities.",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://www.radiant-care-services.com/",
    source: "",
  },
  {
    id: "15",
    image: "/roybits.png",
    title: "Roybits",
    description: "Digital Assets Exchange Web3 platform",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web3",
    link: "https://roybits.vercel.app/",
    source: "",
  },
  {
    id: "16",
    image: "/c-gen.png",
    title: "Conquering Generations",
    description: "A Church Fundraiser platform",
    tech: ["Next Js", "Tailwind", "Css"],
    category: "Web Apps",
    link: "https://demiladeala-getlinked.vercel.app/",
    source: "",
  },
  {
    id: "17",
    image: "/chowopa.png",
    title: "Chowopa",
    description: "A Multistore Ecommerce Website",
    tech: ["React", "Css", "Tailwind"],
    category: "Web Apps",
    link: "https://chowopa-v2-test.netlify.app/",
    source: "https://github.com/Fantom-01/chowopa-v2",
  },
  {
    id: "18",
    image: "/gymapp.png",
    title: "GYM-APP LANDING PAGE",
    description: "Gym Landing page",
    stack: "REACT, TYPESCRIPT, TAILWIND",
    link: "https://gym-app-typescript-jet.vercel.app/",
    source: "https://github.com/Demiladeala/gym-app-typescript",
  },
  {
    id: "19",
    image: "/bookxity.png",
    title: "BOOKXITY",
    description: "Ecommerce website for selling books",
    stack: "NEXT JS, TAILWIND, SANITY",
    link: "https://book-xity-ecommerce.vercel.app/",
    source: "https://github.com/Demiladeala/bookXity_ecommerce",
  },
  {
    id: "20",
    image: "/expense.png",
    title: "REACT EXPENSE TRACKER",
    description: "This is an application for tracking your expense",
    stack: "REACT, CONTEXT API",
    link: "https://react-hooks-and-context-api.vercel.app/",
    source: "https://github.com/Demiladeala/React-hooks-and-Context-API",
  },
];

/*

   {
        id:'4',
        image:'/react-card.webp',
        title: 'Digital Business Card',
        description: 'Business Card built with React',
        stack:'/react.svg',
        link: 'https://business-card-j7jp5ehiy-demiladeala.vercel.app/',
    },
    {
        id:'5',
        image:'/react-page.webp',
        title: 'React Page',
        description: 'Static page built with React',
        stack:'/react.svg',
        link: 'https://mini-project-1-nine.vercel.app/',
    },
    {
        id:'9',
        image:'/css grid and flex.webp',
        title: 'Css flex and grid',
        description: 'Css flexbox and Css grids being implemented from task with ZURI',
        stack:'/css.svg',
        link: 'https://flexbox-and-grid.pages.dev/grid',
    },
    {
        id:'10',
        image:'/css design.webp',
        title: 'Css chatbox design',
        description: 'A chatbox designed with css',
        stack:'/css.svg',
        link: 'https://demiladeala.github.io/DemmyChat/',
    }
 */
