export const projects = [
    {
        id:'1',
        picture:'/topicals-clone.webp',
        name: 'Topicals-clone',
        description: 'Ecommerce Website built with Next js, tailwind and sanity.io',
        stack:'/next.svg',
        link: 'https://topicals-clone.vercel.app/',
    },
    {
        id:'2',
        picture:'/first-portfolio.webp',
        name: 'Frontend Developer Portfolio',
        description: 'Learnt about pages and routes, Links, Layout component, Images and Metadata, Fetching data (getStaticProps), Dynamic routes (getStaticPaths), Fetching a single item by building a simple portfolio with Next js , Framer Motion and Tailwind',
        stack:'/next.svg',
        link: 'https://demiladeala.vercel.app/',
    },
    {
        id:'3',
        picture:'/new-covenant-church.webp',
        name: 'New Covenant Church, Ado-Ekiti',
        description: 'Church Website built with html, css , javascript and php',
        stack:'/html.svg',
        link: 'https://www.newcovenantchurchadoekiti.com.ng/',
    },
    {
        id:'4',
        picture:'/react-card.webp',
        name: 'Digital Business Card',
        description: 'Business Card built with React',
        stack:'/react.svg',
        link: 'https://business-card-j7jp5ehiy-demiladeala.vercel.app/',
    },
    {
        id:'5',
        picture:'/react-page.webp',
        name: 'React Page',
        description: 'Static page built with React',
        stack:'/react.svg',
        link: 'https://mini-project-1-nine.vercel.app/',
    },
    {
        id:'6',
        picture:'/laspag.webp',
        name: 'Ecommerce food website',
        description: 'Pre build of ecommerce website, The aim was to later build the project with react',
        stack:'/javascript.svg',
        link: 'https://la-spag.pages.dev/',
    },
    {
        id:'7',
        picture:'/reg page.webp',
        name: 'Registration page(Form Validation) with js',
        description: 'Registration landing page built with Javascript (FORM VALIDATION) html and css - Task from ZURI',
        stack:'/javascript.svg',
        link: 'https://registration-form.pages.dev/',
    },
    {
        id:'8',
        picture:'/huddle-landingpage.webp',
        name: 'HUDDLE landing page',
        description: 'landing page built with html, css and javscript while learning frontend development in ZURI',
        stack:'/html.svg',
        link: 'https://huddle-landing-page.pages.dev/',
    },
    {
        id:'9',
        picture:'/css grid and flex.webp',
        name: 'Css flex and grid',
        description: 'Css flexbox and Css grids being implemented from task with ZURI',
        stack:'/css.svg',
        link: 'https://flexbox-and-grid.pages.dev/grid',
    },
    {
        id:'10',
        picture:'/css design.webp',
        name: 'Css chatbox design',
        description: 'A chatbox designed with css',
        stack:'/css.svg',
        link: 'https://demiladeala.github.io/DemmyChat/',
    }
]